global:
  username: xxxxxxx
  password: ********
influxdb:
  url: "http://localhost:8086"
  token: "***********"
  org: xxxxxxx
  bucket: xxxxxx
git:
  - url: https://github.com/xxxx/release_metrics_generator.git
  - url: https://github.com/xxxx/fileuploader.git
  - url: https://github.com/xxxx/fileviewer.git

